docs: Minor Clarifications to README
n8n-io/self-hosted-ai-starter-kit pull request #10
Opened 2024-08-24 10:17 UTC by YonLiud

I have made some minor updates to the README file to improve clarity and readability.

Please review and let me know if further adjustments are needed :)

2024-09-16 14:33 UTC, freakwriter approved these changes
@jeanpaul looks good to me!

2024-09-17 07:14 UTC, jeanpaul commented
Hi @YonLiud 
Thank you for your contribution to the Starter Kit! Your PR requires a few merge-conflicts to be resolved, can you fix these?

2024-09-18 18:01 UTC, YonLiud commented
Sure!
I will get right into it in a few moments

2024-09-19 05:42 UTC, YonLiud commented
I believe I’ve resolved the merge conflict in the `README.md`.
Please keep me posted about any other issues

2024-09-19 15:44 UTC, freakwriter requested changes
@YonLiud I added some suggested commits to shift the titles to sentence case, to match the rest of the file. Can you commit those suggestions and then we can merge? These are helpful changes. :)

2024-09-19 15:44 UTC, freakwriter commented on README.md
> +### What You Can Build
```suggestion
### What you can build
```

2024-09-19 15:44 UTC, freakwriter commented on README.md
> +* ### For Nvidia GPU Setups:
```suggestion
* ### For Nvidia GPU setups:
```

2024-09-19 15:44 UTC, freakwriter commented on README.md
> +* ### For Non-GPU Setups:
```suggestion
* ### For Non-GPU setups:
```

2024-09-19 19:01 UTC, YonLiud commented
```git
grep -v -e'^<<<<<<<' -e '^>>>>>>>' -e'=======' filename.txt > filename.txt.merged
```

2024-09-23 17:03 UTC, freakwriter approved these changes
@jeanpaul can you merge this?

2024-09-24 10:16 UTC, jeanpaul approved these changes

2024-09-24 10:16 UTC, merged