Update README.md to make it clearer for running Ollama on Mac locally
n8n-io/self-hosted-ai-starter-kit pull request #14
Opened 2024-08-31 04:34 UTC by kenrickles

2024-09-05 07:36 UTC, jeanpaul requested changes
@kenrickles Thank you for your pull request. I requested some changes, but overall I like your change!

2024-09-05 07:36 UTC, jeanpaul commented on README.md
> +Click on Local Ollama service and change the base url to http://host.docker.internal:11434/
This is relatively hard to read in the web-version of the readme. Also, please use double quotes around the parts that you are quoting.

2024-11-24 18:44 UTC, gepparta commented
Same goes for win11 if you consider this change to docker compose
https://github.com/n8n-io/self-hosted-ai-starter-kit/pull/23

2025-01-04 13:02 UTC, jpcaparas commented
This needs to be merged.

2025-02-02 18:44 UTC, msusol commented
see https://github.com/n8n-io/self-hosted-ai-starter-kit/pull/27 which will incorporate this change that wasn't resolved.

2025-02-06 11:49 UTC, netroy commented
duplicate of #27

2025-02-06 11:49 UTC, closed without merging